print("DESAFIO 2")
dia = input("Informe o dia do seu nascimento: ")
mes = input("Informe o mês do seu nascimento: ")
ano = input("Informe o ano do seu nascimento: ")
print("você nasceu no dia ", dia, " de ", mes, " de ", ano, "! :)")
